# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f76cced8db30489afc20a19ed279fa613095f264d04c26f7a53433a7c501a7bae87649255a1b901c84df826337926366be2fe2cee5c28b4ba45b67d995f28f3

test:
  secret_key_base: 5a2b3b660c2e04ce9fbf8c396ab566446a9d0091b7de2fc0728869ef5cbd3eb6f9a81036218d71721bac8723676d62084683d1cd9ac6c763d4f64e0bc7f67128

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
